server:
  port: 3031
  servlet:
    context-path: /my-security-service

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#
# TO CONNECT H2 CONSOLE refer below
# http://localhost:3031/my-security-service/h2-console/

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Settings for the oracle connection
  datasource:
    url:
      jdbc:oracle:thin:@localhost:1521:xe
    username:
      system
    password:
      12345
    driver-class-oracle:
      jdbc:
        driver:
          OracleDriver
  application:
    name: HOME-SECURITY-SERVICE

# - ENABLED SQL QUERIED - FOR DEV ENVIRONMENT
# - TO SEE SQL QUERIES IN CONSOLE
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
